import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
// import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";

import { TailwindIndicator } from "@/components/layout/tailwind-indicator";
import { ThemeProvider } from "@/components/layout/theme-provider"

import "./globals.css";

interface StickyLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function StickyLayout({ children }: StickyLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
      <body>
    <div className="relative flex min-h-screen flex-col">
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
    <SiteHeader sticky />
      <main className="flex h-full flex-1 flex-col">{children}</main>
          
        <TailwindIndicator />
        </ThemeProvider>
      
      {/* <SiteFooter /> */}
    </div>
    </body>
    </html>
  );
}

